(function(g){var window=this;var z3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.MB(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},A3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},dDa=function(a,b){var c=new g.LB;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},eDa=function(){this.u=[];
this.o=[]},B3=function(a,b){switch(b.kind){case "asr":fDa(b,a.u);
break;default:fDa(b,a.o)}},fDa=function(a,b){g.eb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},C3=function(){g.B.call(this);
this.u=new eDa;this.B=[]},D3=function(a,b,c){C3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.gt},E3=function(){this.segments=[]},gDa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.nb(a.segments,c),g.nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ub(a.segments,c,0,b),g.ub(a.segments,c+1,0,b)))},F3=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.N=c;this.F=d;this.C=e;this.I=f;this.M=this.player.O();this.B=new E3;this.u=this.A=this.o=null;this.G=new g.G(this.vA,1E3,this);this.events=new g.Es(this);g.C(this,this.G);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.sC);this.sC();this.vA()},hDa=function(a,b){var c=g.lw(b,a.policy,{}).xc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.cs(c,d,3,100).then(function(e){a.ga();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.ax(e);h?(e=g.lw(a.A,a.policy,{}),f=a.A,g.hw(f.u,e,h),f.requestId=e.get("req_id"),hDa(a,a.A)):(f||null==a.F||(h=a.A.o[0],a.C?a.F(e.response,1E3*(h.startTime+a.player.Jb())):a.F(e.responseText,1E3*(h.startTime+a.player.Jb()))),a.A=null,a.u=null)});
a.A=b;gDa(a.B,a.A.o[0].u)},G3=function(a,b){C3.call(this,b.O());
this.ia=a;this.H=b;this.o=null;this.A=!1;this.C=g.yz(this.H.O())&&!this.ia.u},iDa=function(a,b){var c=[],d;
for(d in a.ia.o)if(a.ia.o.hasOwnProperty(d)){var e=a.ia.o[d];if(g.jO(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.LB({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},jDa=function(a,b){return null!=b&&b in a.ia.o?a.ia.o[b]:null},kDa=function(a,b,c){var d=[],e;
for(e in a.ia.o)if(a.ia.o.hasOwnProperty(e)){var f=a.ia.o[e];if(g.jO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},H3=function(a,b,c,d,e){C3.call(this,e||null);
this.videoId=b;this.Xz=d;this.C={};this.o=null;b=c||g.xq(a).hl||"";b=b.split("_").join("-");this.A=g.zq(a,{hl:b})},I3=function(a,b,c,d,e,f,h){var l={};
g.Va(l,b);g.Va(l,a.params);g.Va(l,c);var m={};g.Va(m,b.Kb);a.params.Kb&&g.Va(m,a.params.Kb);g.Va(m,c.Kb);l.Kb=m;g.U.call(this,{D:"div",J:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",J:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.U=!1;this.u=a;this.X=this.T=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.F=null;this.maxWidth=.96*e;this.va=.96*f;this.o=l;this.Fa=
c;this.B=this.ba("captions-text");this.Ea=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Y=d/360*16;this.type=0;this.fa=this.Y*lDa(m);a=new g.Ks(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.HI,this);a.subscribe("dragmove",this.GI,this);a.subscribe("dragend",this.FI,this);this.sa=this.na=0;b="";this.o.windowOpacity&&(a=g.v1(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":mDa[this.o.textAlign]};this.Ea&&(a["border-radius"]=b?this.fa/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.ve&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Oh(b,"-o-writing-mode",c),g.Oh(b,"-webkit-writing-mode",c),g.Oh(b,"writing-mode",c),g.Oh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.Oh(b,"text-orientation",
""),g.Oh(b,"transform","rotate(180deg)"));g.Oh(this.element,a);switch(this.o.yf){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},lDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},nDa=function(a,b){var c={},d=b.background?b.background:a.o.Kb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.Kb.backgroundOpacity;d=g.v1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ea&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*lDa(b)+"px";d=1;e=b.color||a.o.Kb.color;if(b.color||null!=b.textOpacity)e=g.v1(e),d=null==b.textOpacity?a.o.Kb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.lt&&(h=e=b.lt);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Bl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Kb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Nf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.gH&&(c.visibility="hidden");1===b.Tz&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Cz||g.Dz,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.eg||2===b.eg||3===b.eg||4===b.eg||5===b.eg)if(g.Cz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.eg){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},oDa=function(a){a.F=g.Ce("SPAN");
g.Oh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},pDa=function(a,b){var c=g.Ce("SPAN");
g.Oh(c,{display:"inline-block","white-space":"pre-wrap"});g.Oh(c,nDa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.Oh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Oh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},qDa=function(a,b,c){a.U=a.U||!!c;
var d={};g.Va(d,a.o.Kb);g.Va(d,c||b.o);g.Va(d,a.Fa.Kb);(c=!a.F)&&oDa(a);for(var e=a.T&&a.X&&g.Sb(d,a.X)?a.T:pDa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(oDa(a),e=pDa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.De(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.Cz||!g.Sh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Sh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.xe?g.Oh(e,m,"1em"):g.Oh(e,m,"0.5em")))}a.X=d;a.T=e;a.C.push(b)},J3=function(a,b,c,d,e,f,h){I3.call(this,a,b,c,d,e,f,h);
this.type=1},K3=function(a,b,c,d,e,f,h){I3.call(this,a,b,c,d,e,f,h);
this.type=2;this.G=[];this.N=this.I=this.Z=0;this.R=NaN;this.ya=0;this.Aa=null;this.ha=new g.G(this.PM,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.ha);g.Oh(this.element,"overflow","hidden")},rDa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},sDa=function(a){if(isNaN(a.R)){var b=a.o.Vh;
if(b){var c=g.Ce("SPAN");g.Le(c,"\u2013".repeat(b));g.Oh(c,nDa(a,a.o.Kb));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},tDa=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},uDa=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.N=Math.max(sDa(a),a.ya,rDa(a,a.B))},vDa=function(a,b){uDa(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!==a.Z){var d=0<c&&0===a.Z;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.ha.gb());g.Oh(a.B,"transform",tDa(a,c));a.Z=c}uDa(a)},L3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Kz.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},M3=function(a,b,c,d,e){g.Kz.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},wDa=function(a){var b="_"+N3++;
return new M3(0,0x8000000000000,0,b,a)},yDa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.lc){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[q.getAttribute("p")];l=xDa(l.textContent,n.textContent,q.textContent,f.textContent,h);return new L3(a,b,e,c,l,d,m)}switch(m.lc){case 9:case 10:m.eg=1;break;case 11:m.eg=2;break;case 12:m.eg=3;break;case 13:m.eg=4;break;case 14:m.eg=5}return new L3(a,b,e,c,l.textContent||"",d,m)},xDa=function(a,b,c,d,e){var f=g.Bl(),h=
f?g.Ce("DIV"):g.Ce("RUBY"),l=g.Ce("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ce("DIV"):g.Ce("RP");a.textContent=b;h.appendChild(a);b=f?g.Ce("DIV"):g.Ce("RT");b.textContent=c;h.appendChild(b);c=e.lc;if(10===c||11===c||12===c||13===c||14===c)if(g.Oh(b,"text-emphasis-style","filled circle"),g.Oh(b,"text-emphasis-color","currentcolor"),g.Oh(b,"webkit-text-emphasis","filled circle"),11===e.lc||13===e.lc)g.Oh(b,"webkit-text-emphasis-position","under left"),g.Oh(b,"text-emphasis-position","under left");c=!0;if(4===e.lc||7===e.lc||12===e.lc||
14===e.lc)g.Oh(h,"ruby-position","over"),g.Oh(h,"-webkit-ruby-position","before");else if(5===e.lc||6===e.lc||11===e.lc||13===e.lc)g.Oh(h,"ruby-position","under"),g.Oh(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ce("DIV"):g.Ce("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Oh(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Oh(f,"display","none"),f=f.nextElementSibling,g.Oh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Oh(h.lastElementChild,"display","none"),d?(g.Oh(h,"padding-top","0.6em"),g.Oh(f,"top","0")):(g.Oh(h,"padding-bottom","0.6em"),g.Oh(f,"bottom","0")));return h},O3=function(){g.B.apply(this,arguments)},P3=function(a){O3.call(this);
this.F=a;this.B={};this.M={};this.N={};this.C="_"+N3++;this.I={};this.u=this.o=null;this.G=!0},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},R3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},S3=function(a,b){var c=Q3(a,b);
return void 0!==c?c:null},U3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return T3.test(c),c},zDa=function(a,b){var c={},d=b.getAttribute("ws");
g.Va(c,d?a.N[d]:a.F);d=S3(b,"mh");null!=d&&(c.vl=d);d=S3(b,"ju");null!=d&&(c.textAlign=d);d=S3(b,"pd");null!=d&&(c.o=d);d=S3(b,"sd");null!=d&&(c.A=d);d=U3(b,"wfc");null!=d&&(c.windowColor=d);d=Q3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},ADa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Va(c,a.M[d]);d=S3(b,"ap");null!=d&&(c.yf=d);d=Q3(b,"cc");null!=d&&(c.Vh=d);d=Q3(b,"ah");null!=d&&(c.Me=d);d=Q3(b,"rc");null!=d&&(c.u=d);d=Q3(b,"av");null!=d&&(c.hg=d);return c},BDa=function(a,b,c,d){var e={};
g.Va(e,ADa(a,b));g.Va(e,zDa(a,b));d?g.Sb(e,a.F)?(d=a.C,e=a.F):d="_"+N3++:d=b.getAttribute("id")||"_"+N3++;a=Q3(b,"t")+c;b=Q3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.Vh,e.Vh=c;return new M3(a,b,0,d,e)},V3=function(a){O3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},W3=function(a){a=g.Yd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},CDa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.Vh=b);if(2===f.o||3===f.o)b=f.u,f.u=f.Vh,f.Vh=b;return new M3(c,d,0,e,f)},Y3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new X3(this);this.C=new X3(this);this.o=[];this.clear()},EDa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{fj:a,
Th:b,result:0};a=DDa[a];b=DDa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Th===d;if(d)return{fj:a,Th:b,result:1}}else if(b&128&&1<=a&&31>=a)return{fj:a,Th:b,result:2};return{fj:a,Th:b,result:3}},GDa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,FDa(a.B,b,c,d))},HDa=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?GDa(a,d.qy,d.ry,b):1===d.type&&a.u&496&&FDa(a.C,d.qy,d.ry,b);a.o.length=0},Z3=function(){this.type=0},$3=function(){this.state=this.Th=this.fj=0},IDa=function(){this.timestamp=this.o=0},a4=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new Z3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new IDa}},b4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!==r.o){0===c&&(c=m,d=q);n=String.fromCharCode(r.o);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.o||32===q)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(q=a.A[h][m],r=q.o,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},NDa=function(a,b){switch(a){case 0:return JDa[(b&127)-32];
case 1:return KDa[b&15];case 2:return LDa[b&31];case 3:return MDa[b&31]}return 0},c4=function(a){return a.A[a.row][a.u]},d4=function(a,b,c){2<=b&&1<a.u&&(--a.u,c4(a).o=0);
var d=c4(a);d.timestamp=a.C.time+0;d.o=NDa(b,c);32>a.u&&a.u++},ODa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},e4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},f4=function(a){a.row=0<a.o?a.o:1;
a.u=1;e4(a,0,15)},g4=function(a){this.A=a;
this.C=0;this.style=new Z3;this.F=new a4(this.A);this.G=new a4(this.A);this.text=new a4(this.A);this.u=this.F;this.B=this.G;this.o=this.u},h4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(b4(d,c),f4(a.u),f4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(b4(d,c),e4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},PDa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},QDa=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},X3=function(a){this.u=a;
this.C=0;this.A=new g4(this.u);this.F=new g4(this.u);this.o=new $3;this.B=this.A},FDa=function(a,b,c,d){a.o.update();
b=EDa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.fj;c=b.Th;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&d4(a,0,b),c&96&&d4(a,0,c),0!==b&&0!==c&&3===a.style.type&&b4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.fj=e,b.Th=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;ODa(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));e4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:d4(b.o,0,32);break a;case 48:57===c?(d=b.o,c4(d).o=0,32>d.u&&d.u++):d4(b.o,1,c&15)}break;case 2:c&32&&d4(b.o,2,c&31);break;case 3:c&32&&d4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:PDa(b);
break;case 33:d=b.o;1<d.u&&(--d.u,c4(d).o=0);break;case 36:d=b.o;b=c4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:h4(b,2,d);break;case 38:h4(b,3,d);break;case 39:h4(b,4,d);break;case 40:d4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);f4(d);QDa(b);break;case 43:QDa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:b4(a,d)}e4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;b4(a,d);ODa(a,b,b+1,a.o-1);e4(a,a.row,1)}break;case 46:e4(b.B,0,15);break;case 47:b4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,PDa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},RDa=function(){},i4=function(a,b,c){this.I=a;
this.G=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.I);this.A=[]},j4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},k4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},l4=function(a,b){O3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new Y3;this.o.u=1<<this.track},m4=function(a){if("string"===typeof a)return!1;
a=new i4(a,8,0);return SDa(a)},SDa=function(a){if(!(a.o<a.u.byteLength)||1380139777!==k4(a))return!1;
a.version=j4(a);if(1<a.version)return!1;j4(a);j4(a);j4(a);return!0},n4=function(){O3.call(this)},TDa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Nf=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var q=h.childNodes[n];if(3===q.nodeType)q=new L3(b,c,d,e.id,q.nodeValue,f||0<n,g.Qb(l)?void 0:l),m.push(q),e.o.push(q);else{var r={};g.Va(r,l);TDa(a,b,c,d,e,!0,q,r,m)}}},o4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},UDa=function(a,b,c,d){d=Object.assign({vl:0},d);
return new M3(a,b,c,"_"+N3++,d)},p4=function(a){g.B.call(this);
this.u=a;this.o=null},WDa=function(a){var b={};
if(a=A3(a))b.lang=a,VDa.test(a)&&(b.o=1);return b},s4=function(a){g.iO.call(this,a);
this.H=a;this.A=this.H.O();this.videoData=this.H.getVideoData();this.va=g.EN(this.H);this.B={Kb:{}};this.F={Kb:{}};this.R=[];this.M={};this.da={};this.T=!1;this.na=g.kO(this.videoData,this.H);this.ya=!!this.videoData.captionTracks.length;this.Aa=!!this.videoData.qm;this.fa="3"===this.A.controlsType;this.u=this.G=this.I=this.Z=this.ra=null;this.ha=new p4(this.A);this.o=null;this.X=new g.Es(this);var b=null,c=g.Jo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.uo(c));this.storage=b;b=a.app.C;
c=!(!b||!b.mo());this.sa=!(!b||!b.tk());this.C=this.fa&&c&&!this.na;this.N=!this.C&&this.fa&&this.sa&&this.na;g.C(this,this.ha);this.C?this.Y=this.U=null:(this.U=new g.Un(this.VD,void 0,this),g.C(this,this.U),this.Y=new g.G(this.mO,2E3,this),g.C(this,this.Y));g.C(this,this.X);this.C||this.X.L(a,"resize",this.Zw);this.X.L(a,"onPlaybackAudioChange",this.EK);this.X.L(a,g.Nz("captions"),this.II,this);this.X.L(a,"crx_captions",this.JI,this);q4(this,r4(this,"display-settings")||{})},t4=function(a){if(1===
a.A.Xg||1===a.videoData.Xg||"alwayson"===g.HC(a.videoData,"yt:cc"))return!0;
if(2===a.A.Xg){var b=r4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().A;return"ON"===c||"on"===g.HC(a.videoData,"yt:cc")},u4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.u||"FORCED_ON"===c.A},w4=function(a,b){if(a.u){if(a.G&&a.G.C)return a.G.C;
var c=b;c||(c=a.Aa?!1:a.ya?!1:!0);c=a.u.zj(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.HC(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(A3(c[f])===d[e])return c[f];return a.G&&a.G.B?a.G.B:(d=c.find(function(h){return h.isDefault}))?d:c[0]||v4(a)}return null},v4=function(a){return a.G&&a.G.u},x4=function(a){var b=v4(a);
return!!b&&a.o===b},XDa=function(a,b){for(var c=a.H.app.C.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},z4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.T=c,a.T&&y4(a,"module-enabled",!!b));a.o=b;u4(a)&&(a.o=v4(a));a.load()},YDa=function(a,b){var c=a.va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&VDa.test(d)&&(b.params.o=1);d=a.va.getPlayerSize();switch(null!=b.params.vl?b.params.vl:1<b.o.length?1:0){case 1:return new J3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new K3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new I3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},q4=function(a,b,c){c=void 0===c?!1:c;
var d=A4.Kb;a.B={};g.Va(a.B,A4);a.B.Kb={};g.Va(a.B.Kb,d);a.F={Kb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;T3.test(f);e.Kb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;T3.test(f);e.Kb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||A4.windowColor;T3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Kb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Kb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Nf?3:d.bold?1:d.Nf?2:0);f=f.Kb;switch(e){case 1:f.bold=!0;delete f.Nf;break;case 2:delete f.bold;f.Nf=!0;break;case 3:f.bold=!0;f.Nf=!0;break;default:delete f.bold,delete f.Nf}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Kb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=A4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Kb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Kb.fontFamily=f;a.loaded&&a.Zw();c&&y4(a,"display-settings",b)},$Da=function(a,b){if(b&&!a.I){var c=wDa({o:0,
lang:"en"});a.I=[c,new L3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.RN(a.player,a.I)}else!b&&a.I&&(ZDa(a,a.I),a.I=null)},ZDa=function(a,b){g.PT(a.player.app,b,void 0);
g.y(b,function(c){g.ob(this.R,c)},a);
a.U.gb()},r4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},y4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.rD.prototype.sm=g.ca(11,function(){for(var a=g.me(document,"track",void 0,this.o),b=0;b<a.length;b++)g.He(a[b])});
g.ES.prototype.sm=g.ca(10,function(){this.o.sm()});
g.rD.prototype.mo=g.ca(9,function(){return!!this.o.textTracks});
g.ES.prototype.mo=g.ca(8,function(){return this.o.mo()});
g.rD.prototype.mm=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.ES.prototype.mm=g.ca(6,function(a){this.o.mm(a)});
g.iD.prototype.tk=g.ca(5,function(){});
g.rD.prototype.tk=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.ES.prototype.tk=g.ca(3,function(){return this.o.tk()});
g.Pt.prototype.Rp=g.ca(1,function(a){return(a=this.rg(a))?a.o:0});
g.Uw.prototype.Rp=g.ca(0,function(){return 0});
var VDa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;eDa.prototype.zj=function(a){return a?this.o.concat(this.u):this.o};
g.t(C3,g.B);g.k=C3.prototype;g.k.zj=function(a){return this.u.zj(a)};
g.k.tq=function(){};
g.k.uq=function(){};
g.k.Kh=function(){};
g.k.Wk=function(){return""};
g.k.NC=function(){return!1};
g.k.W=function(){this.Kh();g.B.prototype.W.call(this)};
g.t(D3,C3);D3.prototype.tq=function(a,b,c){var d=this;this.ga();b=this.Wk(a,b);this.Kh();this.o=g.Pq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
D3.prototype.uq=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())B3(this.u,c.value);a()};
D3.prototype.Wk=function(a,b){var c=a.xc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.Bl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=A3(a));return g.zq(c,d)};
D3.prototype.Kh=function(){this.o&&this.o.abort()};
E3.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
E3.prototype.length=function(){return this.segments.length/2};
g.t(F3,g.B);g.k=F3.prototype;g.k.W=function(){g.B.prototype.W.call(this);this.u&&this.u.cancel()};
g.k.sC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Jb();var b=this.o;this.o=g.cb(this.N.lh(a).o);b!==this.o&&this.I&&this.I()};
g.k.reset=function(){this.B=new E3;this.u&&(this.u.cancel(),this.u=null)};
g.k.vA=function(){this.ga();var a;if(a=null!=this.o)a=this.o,a=a.o.Bh(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.di(),a.o[0].duration?(this.B.contains(a.o[0].u)||hDa(this,a),this.o=g.cb(a.o)):!g.R(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.F&&this.o.F+this.player.Jb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.t(G3,C3);g.k=G3.prototype;g.k.tq=function(a,b,c){var d=this;this.Kh();b=jDa(this,a.getId());b||(b=a.languageCode,b=this.ia.u?kDa(this,b,"386"):kDa(this,b));if(b){var e=1E3*(b.index.Rp(b.index.Hf())-b.index.sd(b.index.Hf()));this.o=new F3(new g.Ev,this.H,b,function(f,h){c(f,a,h,e)},this.C||g.uv(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.NC=function(){var a=this.A;this.A=!1;return a};
g.k.uq=function(a){var b;this.C?b=[new g.LB({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.LB({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ia.u?iDa(this,"386"):iDa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())B3(this.u,c.value);a()};
g.k.Kh=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.Wk=function(){return""};
g.t(H3,C3);H3.prototype.tq=function(a,b,c){var d=this;this.ga();b=this.Wk(a,b);this.Kh();this.o=g.Pq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
H3.prototype.uq=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Xz&&(d.asrs=1);c=g.zq(c,d);this.Kh();this.o=g.Pq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),r=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),A="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");B3(b.u,new g.LB({languageCode:m,languageName:n,name:q,kind:r,id:u,is_servable:!0,is_translateable:A,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
H3.prototype.Wk=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=A3(a));return c=g.zq(c,d)};
H3.prototype.Kh=function(){this.o&&this.o.abort()};
var T3=/^#(?:[0-9a-f]{3}){1,2}$/i;var mDa=["left","right","center","justify"];g.t(I3,g.U);g.k=I3.prototype;g.k.HI=function(a,b){var c=g.di(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.GI=function(a,b){var c=g.gi(this.element),d=a-this.na-.02*this.playerWidth,e=b-this.sa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Yd(f,0,2));var h=(e+c.height/2)/this.va*3;h=Math.floor(g.Yd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Yd(d,0,1);c=(e+h/2*c.height)/this.va;c=100*g.Yd(c,0,1);this.u.params.yf=l;this.u.params.hg=c;this.u.params.Me=d;this.o.yf=l;this.o.hg=c;this.o.Me=d;this.oD()};
g.k.FI=function(){g.co(this.element,"ytp-dragging")};
g.k.oD=function(){this.pk(this.C)};
g.k.pk=function(a){var b=Math.min(this.mz(),this.maxWidth),c=this.lz(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.Oh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Us(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Me+2;d=this.o.yf;switch(d){case 0:case 3:case 6:b=this.o.Kb.fontSizeIncrement;!g.R(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.hg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.Oh(this.element,a)};
g.k.Us=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.U||this.C.length>b)b=0,this.U=!1,this.C=[],this.F=this.X=this.T=null,g.Fe(this.B);for(;b<a.length;b++)qDa(this,a[b])};
g.k.mz=function(){return 0};
g.k.lz=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};g.t(J3,I3);J3.prototype.Us=function(a){var b=this.u.o;I3.prototype.Us.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Va(d,c.o);g.Va(d,aEa);var e=c.o;var f=d}qDa(this,c,d)}};
var aEa={gH:!0};g.t(K3,I3);g.k=K3.prototype;g.k.oD=function(){g.Xn(this.ha)};
g.k.PM=function(){g.co(this.element,"ytp-rollup-mode");this.pk(this.Aa,!0)};
g.k.lz=function(){return this.A?this.N:this.I};
g.k.mz=function(){return this.A?this.I:this.N};
g.k.pk=function(a,b){this.Aa=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.N;this.I=this.N=0;I3.prototype.pk.call(this,a);vDa(this,b);I3.prototype.pk.call(this,a)}else I3.prototype.pk.call(this,a)};g.t(L3,g.Kz);L3.prototype.toString=function(){return g.Kz.prototype.toString.call(this)};g.t(M3,g.Kz);M3.prototype.toString=function(){return g.Kz.prototype.toString.call(this)};
var N3=0;g.t(O3,g.B);O3.prototype.A=function(){return[]};
O3.prototype.reset=function(){};g.t(P3,O3);P3.prototype.reset=function(){this.I={};this.u=this.o=null;this.G=!0};
P3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Va(l,this.B[m]);m=R3(c,"b");null!=m&&
(l.bold=m);m=R3(c,"i");null!=m&&(l.Nf=m);m=R3(c,"u");null!=m&&(l.underline=m);m=S3(c,"et");null!=m&&(l.charEdgeStyle=m);m=S3(c,"of");null!=m&&(l.offset=m);m=U3(c,"bc");null!=m&&(l.background=m);m=U3(c,"ec");null!=m&&(l.lt=m);m=U3(c,"fc");null!=m&&(l.color=m);m=S3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=Q3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=Q3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=Q3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=S3(c,"rb");null!=m&&10!==m&&0!==m&&(l.lc=
10<m?m-1:m);c=S3(c,"hg");null!=c&&(l.Tz=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.N[d]=zDa(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=ADa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=BDa(this,d,e,!1);(d=this.I[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.I[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!R3(d,
"a");n=(Q3(d,"t")||0)+n;var q=Q3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var A=0;A<w.length;A++){var z=w[A],E=void 0;0<A&&(m=!0);var D=void 0;1===z.nodeType&&(D=z);if(D&&"s"===D.tagName){if((z=(z=D.getAttribute("p"))?this.B[z]:null)&&z.lc&&(1===z.lc?(z=w.slice(A,A+4),4===z.length&&
(E=yDa(n,q,l,m,r,z,this.B),A+=3)):E=yDa(n,q,l,m,r,[D],this.B)),!E){var H=D;E=n;D=q;z=l;var P=m,Q=r,Ja=H.textContent?H.textContent:"",Na=H.getAttribute("p");Na=Na?this.B[Na]:null;H=Q3(H,"t")||0;E=new L3(E+H,D-H,Q,z,Ja,P,Na)}}else E=new L3(n,q,r,l,z.textContent||"",m,u);h.push(E);this.u=E}if(0<h.length)for(h[0].windowId===this.C&&(this.o=BDa(this,d,e,!0),c.push(this.o)),d=g.p(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var bEa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.t(V3,O3);V3.prototype.reset=function(){this.u.clear()};
V3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Nf=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.lt=W3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=W3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=W3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.lc=10<l?l-1:l,h.eg=bEa.get(h.lc));f.hgHorizGroup&&(h.Tz=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.F),void 0!==f.mhModeHint&&(h.vl=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=W3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Me=f.ahHorPos),void 0!==f.apPoint&&(h.yf=f.apPoint),void 0!==f.avVerPos&&(h.hg=f.avVerPos),void 0!==f.ccCols&&(h.Vh=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=CDa(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+N3++,l=CDa(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,q=n?6:5,r=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],A=w.utf8;if(A){var z=w.tOffsetMs||0,E=null;w.pPenId&&(E=this.o.get(w.pPenId));if(2===(null!=l.params.vl?l.params.vl:1<l.o.length?1:0)&&n&&"\n"===A)continue;if(w=E&&1===E.lc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var D=r[w+1].pPenId;(D=this.o.get(D))&&D.lc&&2===D.lc?(D=r[w+2].pPenId,D=this.o.get(D),!D||!D.lc||3>D.lc?w=!1:(D=r[w+3].pPenId,w=(D=this.o.get(D))&&
D.lc&&2===D.lc?!0:!1)):w=!1}if(w){z=r[m+1].utf8;w=r[m+3].utf8;D=r[m+2].utf8;var H=this.o.get(r[m+2].pPenId);A=xDa(A,z,D,w,H);n=new L3(e,f,q,h,A,n,E);m+=3}else n=new L3(e+z,f-z,q,l.id,A,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};Y3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
Y3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var DDa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Z3.prototype.set=function(a){this.type=a};
Z3.prototype.get=function(){return this.type};
$3.prototype.clear=function(){this.state=0};
$3.prototype.update=function(){this.state=2===this.state?1:0};
$3.prototype.isValid=function(){return 0!==this.state};
$3.prototype.matches=function(a,b){return this.isValid()&&a===this.fj&&b===this.Th};
IDa.prototype.reset=function(){this.timestamp=this.o=0};
a4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
a4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
a4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var JDa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],KDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],LDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],MDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];g4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
X3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};RDa.prototype.C=function(){};g.t(i4,RDa);i4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+N3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new M3(c,d-c,5,f,{textAlign:0,yf:0,Me:2.5*b,hg:5.33*a});e=new L3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.t(l4,O3);l4.prototype.A=function(a){a=new i4(a,a.byteLength,this.u);if(SDa(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=k4(a)*(1E3/45):1===a.version&&(a.B=4294967296*k4(a)+k4(a)),a.F=j4(a);0<a.F;a.F--){var b=j4(a),c=j4(a),d=j4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,qy:c,ry:d,order:b.o.length}))}HDa(this.o,a);return a.A}return[]};
l4.prototype.reset=function(){this.o.clear()};g.t(n4,O3);
n4.prototype.A=function(a,b){for(var c=[],d=a.split(cEa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!dEa.test(f)){var l=B4.exec(f);if(l&&4<=l.length){var m=o4(l[1]),n=o4(l[2])-m;m+=h;var q=(l=l[3])?l.split(" "):[];l={};var r=null,u="",w=null,A="";l.textAlign=2;q=g.p(q);for(var z=q.next();!z.done;z=q.next())if(z=z.value.split(":"),2===z.length){var E=z[1];switch(z[0]){case "line":z=E.split(",");z[0].endsWith("%")&&(r=z[0],l.hg=Number.parseInt(r,10),2===z.length&&(u=z[1].trim()));break;case "position":z=
E.split(",");w=z[0];l.Me=Number.parseInt(w,10);2===z.length&&(A=z[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.hg=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.Me=0;break;case 1:l.Me=100;break;default:l.Me=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(A){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.yf=0>r||8<r?7:r;f=f.substring(B4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");A=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=UDa(m,n,5,A),n=new L3(m,n,5,h.id,l,!1,g.Qb(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(u=l.split(eEa),1===u.length?(l=5,A=UDa(m,n,l,A)):(r=l=6,A=Object.assign({Vh:32},A),A=new M3(m,n,r,"_"+N3++,A)),c.push(A),r=m,w=0;w<u.length;w++)q=u[w],0===w%2?(z=g.w1("<html>"+q+"</html>"),z.getElementsByTagName("parsererror").length?
(E=z.createElement("span"),E.appendChild(z.createTextNode(q))):E=z.firstChild,TDa(this,r,n-(r-m),l,A,0<w,E,f,c)):r=o4(q)+h}B4.lastIndex=0}}return c};
var dEa=/^NOTE/,cEa=/(?:\r\n|\r|\n){2,}/,B4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),eEa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(p4,g.B);p4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
p4.prototype.reset=function(){this.o&&this.o.reset()};
p4.prototype.W=function(){g.B.prototype.W.call(this);this.clear()};var A4={windowColor:"#080808",windowOpacity:0,textAlign:2,yf:7,Me:50,hg:100,Kb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(s4,g.iO);g.k=s4.prototype;g.k.W=function(){if(this.C||this.N){var a=this.H.app.C;a&&!a.ga()&&a.sm()}else $Da(this,!1);g.iO.prototype.W.call(this)};
g.k.load=function(){var a=this;g.iO.prototype.load.call(this);var b=!g.R(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.ha.clear(),this.C?XDa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.tq(this.o,"json3",function(d,e,f,h){if(d){a.u.NC()&&(a.R=[],g.dR(a.H.app,"captions",void 0),a.U.gb(),a.ha.reset());var l=a.ha;f=f||0;h=h||0;if(l.u.ea("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.eu(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),m4(d)||(d=g.pg(new Uint8Array(d))))}}else"string"===typeof d||m4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.eu(m,0,1835295092))&&m.size?g.pg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,r=h;if(!m4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new l4(r,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.o||(l.o=new n4),q=l.o.A(e,r),.01>Math.random()&&g.Rr(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new V3(WDa(e)));n=l.o.A(q,f);break b}catch(H){g.Pr(H);n=[];break b}r=g.w1(q);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.o||(l.o=new P3(WDa(e),l.u));n=l.o.A(r,f);break b}var A=Error("Unsupported subtitles format in web player (Format2)");
A.params=q;throw A;}if("transcript"===r.firstChild.tagName){var z=Error("Unsupported subtitles format in web player (Format1)");z.params=q;throw z;}var E=Error("Invalid caption track data");E.params=q;throw E;}u=n}var D=u}catch(H){g.Pr(H),l.clear(),D=[]}else D=[];g.RN(a.player,D);!a.T||a.N||x4(a)||g.mz(a.A)||g.nz(a.A)||(a.Y.Ff(),D=wDa({yf:0,Me:5,hg:5,u:2,textAlign:0,o:0,lang:"en"}),a.Z=[D],l=["Click "," for settings"],a.ra||(u=new g.RD(g.aP()),g.C(a,u),a.ra=u.element),u=D.end-D.start,(e=g.MB(a.o))&&
a.Z.push(new L3(D.start,u,0,D.id,e)),a.Z.push(new L3(D.start,u,0,D.id,l[0]),new L3(D.start,u,0,D.id,a.ra,!0),new L3(D.start,u,0,D.id,l[1],!0)),g.RN(a.player,a.Z),a.Y.gb());!a.T||a.N||x4(a)||(y4(a,"module-enabled",!0),a.G&&(a.G.C=a.o),(D=g.V(a.player.app))&&g.JK(D.G));a.T=!1}}),!b||this.C||this.N||x4(this)||this.player.oa("captionschanged",z3(this.o))),b||(this.o&&!x4(this)?this.player.oa("captionschanged",z3(this.o)):this.player.oa("onCaptionsTrackListChanged"));
else{var c;this.na?c=new G3(this.videoData.ia,this.player):this.ya?c=new D3(this.A,this.videoData,this.player.getAudioTrack()):c=new H3(this.videoData.qm,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.HC(this.videoData,"yt:cc_default_lang")||this.A.Yd,this.videoData.ht,this.A);this.u=c;g.C(this,this.u);c.uq(function(){var d;a.T||t4(a)?d=w4(a,a.T):u4(a)&&(d=v4(a));if(a.C||a.N){for(var e=a.u.zj(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.Be("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.MB(l));m.setAttribute("srclang",A3(l));m.setAttribute("id",l.toString());a.N||m.setAttribute("src",a.u.Wk(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.H.app.C;d.mm(f);f=d.xa();a.sa&&a.X.L(f.textTracks,"change",a.rN)}else!a.o&&d&&z4(a,d),a.player.oa("onCaptionsTrackListChanged"),a.player.oa("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?XDa(this,!1):(this.Y&&this.Y.Ff(),g.dR(this.player.app,"captions",void 0),this.R=[],this.u&&this.u.Kh(),this.ha.clear(),this.I&&g.RN(this.player,this.I),this.Zw());g.iO.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.JK(a.G);this.player.oa("captionschanged",{})};
g.k.create=function(){(this.fa?this.C||this.N:u4(this)||t4(this))&&this.load()};
g.k.getTrackById=function(a){for(var b=this.u.zj(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.k.rN=function(){for(var a=this.H.app.C.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&z4(this,b,!0)};
g.k.YO=function(){!this.o&&this.C||this.unload()};
g.k.II=function(a){this.R.push(a);this.U.gb()};
g.k.JI=function(a){g.ob(this.R,a);this.u instanceof G3&&this.u.C&&g.PT(this.player.app,[a],void 0);this.U.gb()};
g.k.fO=function(a){if(a instanceof M3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=YDa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.da[b]||(this.da[b]=[]),this.da[b].push(a)};
g.k.mO=function(){ZDa(this,this.Z);this.Z=null};
g.k.VD=function(){var a=this;this.U.stop();g.Rb(this.da);this.R.sort(g.Mz);var b=this.R;if(this.I){var c=g.Ie(b,function(d){return-1===this.I.indexOf(d)},this);
c.length&&(b=c)}g.y(b,this.fO,this);g.Db(this.M,function(d,e){a.da[e]?(d.element.parentNode||(d instanceof K3||d instanceof J3||g.Gb(a.M,function(f,h){h!==e&&f.u.params.yf===d.u.params.yf&&f.u.params.Me===d.u.params.Me&&f.u.params.hg===d.u.params.hg&&(f.dispose(),delete a.M[h]);return h===e},a),g.VN(a.player,d.element,4)),d.pk(a.da[e])):(d.dispose(),delete a.M[e])},this)};
g.k.sO=function(){q4(this,{},!0);g.R(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.oa("captionssettingschanged")};
g.k.zG=function(){var a=A4.Kb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Nf?3:a.bold?1:a.Nf?2:0,textOpacity:a.textOpacity,windowColor:A4.windowColor,windowOpacity:A4.windowOpacity};var b=r4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.cE=function(a,b){var c={};g.Va(c,r4(this,"display-settings"));g.Va(c,a);q4(this,c,b);this.player.oa("captionssettingschanged")};
g.k.Zw=function(){!this.C&&this.loaded&&(g.Db(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.VD())};
g.k.dd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Yd(b,-2,4);this.cE({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&z4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&y4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ra(b))break;if(g.Qb(b)){z4(this,null,!0);break}for(var d=this.u.zj(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
dDa(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||z4(this,c,!0)}else return this.loaded&&this.o&&!x4(this)?z3(this.o):{};return"";case "tracklist":return this.u?g.Mc(this.u.zj(!(!b||!b.includeAsr)),function(h){return z3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||$Da(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.GH=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.RO=function(){this.loaded&&this.o&&!x4(this)?(y4(this,"module-enabled",!1),this.unload(),u4(this,!0)&&z4(this,v4(this),!1)):z4(this,x4(this)||!this.o?w4(this,!0):this.o,!0)};
g.k.EK=function(){var a=x4(this);u4(this,a)?z4(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.C||this.N:u4(this)||t4(this))&&(a?z4(this,w4(this),!1):this.load()))};g.tO.captions=s4;})(_yt_player);
